parameters:
  git_dir: .
  bin_dir: vendor/bin
  tasks:
    phpcs:
      standard: vendor/voyager/php-quality-tools/configs/phpcs.xml
      triggered_by: ['php']
    phpstan:
      configuration: vendor/voyager/php-quality-tools/configs/phpstan.neon
      level: 5
      triggered_by: ['php']
